Rails.application.routes.draw do
  get 'account_activations/edit'
  get 'microposts/create'
  get 'microposts/destroy'
  get 'password_resets/create'
  get 'password_resets/update'
  get 'relationships/create'
  get 'relationships/destroy'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/create'
  get 'users/edit'
  get 'users/update'
  get 'users/destroy'
  get 'users/following'
  get 'users/follower'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
